<a href="https://colab.research.google.com/github/arddrasoni-commits/13_Data_Binning_and_Formatting/blob/main/experiment_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 13
# Data Binning and Data Formatting using Python
## Arddra Soni
## 25070123022
## ENTC A1

In [ ]:
import pandas as pd
import numpy as np
data = {
    'Product': ['tuner keys', 'Allen Key', 'Bridge nut', 'scale bar'],
    'Price' :[530, 390, 780, 1000],
    'Units_Sold' : [7,45,22,89]
}

df = pd.DataFrame(data)
print("Data Set")
df

Data Set

      Product  Price  Units_Sold
0  tuner keys    530           7
1   Allen Key    390          45
2  Bridge nut    780          22
3   scale bar   1000          89

In [ ]:
# Data Binning
bins = [0,200,500,1000]
labels = ['Low','Medium','High']

df['Price Category'] = pd.cut(df['Price'],bins = bins, labels=labels)
df

      Product  Price  Units_Sold Price Category
0  tuner keys    530           7           High
1   Allen Key    390          45         Medium
2  Bridge nut    780          22           High
3   scale bar   1000          89           High

In [ ]:
# Binning Units Sold
bins2 = [0,30,60,100]
labels2 = ['Low Sales','Medium Sales','High Sales']

df ['Sales_Category']= pd.cut(df['Units_Sold'], bins = bins2, labels = labels2)
print(df)

      Product  Price  Units_Sold Price Category Sales_Category
0  tuner keys    530           7           High      Low Sales
1   Allen Key    390          45         Medium   Medium Sales
2  Bridge nut    780          22           High      Low Sales
3   scale bar   1000          89           High     High Sales

In [ ]:
# Data Formatting
# Convert Data type

print(df.dtypes)

df['Units_Sold'] = df['Units_Sold'].astype(float)

print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price Category    category
Sales_Category    category
dtype: object

In [ ]:
# Convert Text to Uppercase
df['Product'] = df['Product'].str.upper()

print(df)

      Product  Price  Units_Sold Price Category Sales_Category
0  TUNER KEYS    530         7.0           High      Low Sales
1   ALLEN KEY    390        45.0         Medium   Medium Sales
2  BRIDGE NUT    780        22.0           High      Low Sales
3   SCALE BAR   1000        89.0           High     High Sales

In [ ]:
# Rounding Values
df['Price'] = df['Price'].round(2)
df

      Product  Price  Units_Sold Price Category Sales_Category
0  TUNER KEYS    530         7.0           High      Low Sales
1   ALLEN KEY    390        45.0         Medium   Medium Sales
2  BRIDGE NUT    780        22.0           High      Low Sales
3   SCALE BAR   1000        89.0           High     High Sales

In [ ]:
# Additional operations
# Sort Data
sorted_df = df.sort_values(by = 'Price')
print(sorted_df)

      Product  Price  Units_Sold Price Category Sales_Category
1   ALLEN KEY    390        45.0         Medium   Medium Sales
0  TUNER KEYS    530         7.0           High      Low Sales
2  BRIDGE NUT    780        22.0           High      Low Sales
3   SCALE BAR   1000        89.0           High     High Sales

In [ ]:
# Display Unique Values
print(df['Price Category'].unique())

['High', 'Medium']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [ ]:
# Dataset: Food Delivery Orders
import pandas as pd
import numpy as np

data ={
    'Order ID': [101,102,103,104,105],
    'Order_Value': [230,670,450,560,890],
    'Delivery_Time': [30,45,60,25,30],
    'Distance_km':[5,7,12,8,9]
}

df = pd.DataFrame(data)
print("Data Set")
df

Data Set

   Order ID  Order_Value  Delivery_Time  Distance_km
0       101          230             30            5
1       102          670             45            7
2       103          450             60           12
3       104          560             25            8
4       105          890             30            9

In [ ]:
 # Binning Order Value
bins = [0,200,400,700]
labels = ['Low Order','Medium Order','High Order']

df ['Order_Category']= pd.cut(df['Order_Value'], bins = bins2, labels = labels2)
print(df)

   Order ID  Order_Value  Delivery_Time  Distance_km Order_Category
0       101          230             30            5            NaN
1       102          670             45            7            NaN
2       103          450             60           12            NaN
3       104          560             25            8            NaN
4       105          890             30            9            NaN

In [ ]:
# Binning Delivery Time
bins2 = [0,30,45,60]
labels2 = ['Fast','Average','Slow']

df['Delivery_Speed']= pd.cut(df['Delivery_Time'], bins = bins2, labels = labels2)
print(df)

   Order ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       101          230             30            5            NaN
1       102          670             45            7            NaN
2       103          450             60           12            NaN
3       104          560             25            8            NaN
4       105          890             30            9            NaN

  Delivery_Speed    Speed
0           Fast     Fast
1        Average  Average
2           Slow     Slow
3           Fast     Fast
4           Fast     Fast

In [ ]:
# Data Formatting Examples
# Convert Distance to Float
df['Distance_km'] = df['Distance_km'].astype(float)
print(df)

   Order ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       101          230             30          5.0            NaN
1       102          670             45          7.0            NaN
2       103          450             60         12.0            NaN
3       104          560             25          8.0            NaN
4       105          890             30          9.0            NaN

  Delivery_Speed    Speed
0           Fast     Fast
1        Average  Average
2           Slow     Slow
3           Fast     Fast
4           Fast     Fast

In [ ]:
# Convert Order_ID to uppercase
df['Order ID'] = df['Order ID'].str.upper()
print(df)

AttributeError: Can only use .str accessor with string values!

In [ ]:
order_value_mean = df['Order_Value'].mean()
print(order_value_mean)

560.0